package info.bliki.api;

import java.util.ArrayList;
import java.util.List;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

import info.bliki.util.Throwables;
import lombok.extern.slf4j.Slf4j;

/**
 * Reads <code>PageInfo</code> data from an XML file generated by the
 * <a href="https://meta.wikimedia.org/w/api.php">Wikimedia API</a> through the <code>categorymembers</code> query.
 */
@Slf4j
public class XMLCategoryMembersParser extends AbstractXMLParser {

	private static final String CM_TAG = "cm";
	private static final String CONTINUE_TAG = "continue";
	private static final String CMCONTINUE_ID = "cmcontinue";

	private PageInfo fPage;

	private final List<PageInfo> pagesList;

	private String cmContinue;

	public XMLCategoryMembersParser(final String xmlText) throws SAXException {
		super(xmlText);
		pagesList = new ArrayList<>();
		cmContinue = "";
	}

	@Override
	public void endElement(final String uri, final String name, final String qName) {
		try {
			if (CM_TAG.equals(qName)) {// ||
				// CATEGORY_ID.equals(qName))
				// {
				if (fPage != null) {
					pagesList.add(fPage);
				}
				// System.out.println(getString());
			}

			fData = null;
			fAttributes = null;

		} catch (final RuntimeException e) {
			Throwables.log(log, e);
		}
	}

	/**
	 * @return the cmContinue
	 */
	public String getCmContinue() {
		if (cmContinue == null) {
			return "";
		}
		return cmContinue;
	}

	public List<PageInfo> getPagesList() {
		return pagesList;
	}

	@Override
	public void startElement(final String namespaceURI, final String localName, final String qName,
			final Attributes atts) {
		fAttributes = atts;

		if (CM_TAG.equals(qName)) {
			fPage = new PageInfo();
			fPage.setPageid(fAttributes.getValue(AbstractXMLParser.PAGE_ID));
			fPage.setNs(fAttributes.getValue(AbstractXMLParser.NS_ID));
			fPage.setTitle(fAttributes.getValue(AbstractXMLParser.TITLE_ID));
		} else if (CONTINUE_TAG.equals(qName)) {
			final String value = fAttributes.getValue(CMCONTINUE_ID);
			if (value != null) {
				cmContinue = value;
			}
		}
		fData = null;
	}

}
